name: Maven Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Usa l'ultima versione di Ubuntu come ambiente di esecuzione

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Scarica il codice dalla tua repo

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Distribuzione OpenJDK di Eclipse Temurin
          java-version: '17'  # Versione di Java da usare
          cache: 'maven'  # Abilita la cache per velocizzare le build successive

      - name: Build con Maven
        run: mvn -B package --file pom.xml
